import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight } from "lucide-react";
import { ContentPage } from "@/components/ContentPage";
import { Reveal } from "@/components/Reveal";
import { supabase } from "@/integrations/supabase/client";
const title="Blog de Desarrollo Web y Negocios Digitales | Byto";const description="Guías de Byto sobre desarrollo web, e-commerce, SEO, Google Business y tecnología para negocios.";const db=supabase as any;
export const Route=createFileRoute("/blog")({head:()=>({meta:[{title},{name:"description",content:description}],links:[{rel:"canonical",href:"/blog"}]}),component:Page});
type Post={id:string;slug:string;title:string;excerpt:string;image_url:string|null;category:string;tags:string;published_at:string|null};
function Page(){const{data:posts=[],isLoading}=useQuery<Post[]>({queryKey:["blog-posts"],queryFn:async()=>{const{data,error}=await db.from("blog_posts").select("id,slug,title,excerpt,image_url,category,tags,published_at").eq("is_published",true).order("published_at",{ascending:false});if(error)throw error;return data??[];}});return <ContentPage eyebrow="Blog" title="Ideas y guías para tomar mejores decisiones digitales" intro="Contenido práctico sobre sitios web, ventas online, posicionamiento y herramientas digitales para empresas y emprendimientos.">{isLoading?<p className="text-muted-foreground">Cargando publicaciones…</p>:posts.length===0?<Reveal className="glass-panel rounded-3xl border border-border p-8"><h2 className="font-display text-2xl font-bold">Estamos preparando nuevos contenidos</h2><p className="mt-3 text-muted-foreground">Pronto encontrarás aquí guías prácticas sobre desarrollo web, SEO y negocios digitales.</p></Reveal>:<div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{posts.map((post,i)=><Reveal key={post.id} delay={i*50}><Link to="/blog/$slug" params={{slug:post.slug}} className="glass-panel group block h-full overflow-hidden rounded-3xl border border-border">{post.image_url&&<img src={post.image_url} alt="" className="aspect-[16/9] w-full object-cover"/>}<div className="p-6"><p className="text-xs font-semibold uppercase tracking-wider text-primary">{post.category||"Byto"}</p><h2 className="mt-3 font-display text-2xl font-bold">{post.title}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{post.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-primary group-hover:gap-3">Leer artículo <ArrowRight className="h-4 w-4"/></span></div></Link></Reveal>)}</div>}</ContentPage>}
